include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
  errors:
    close_sinks: error

linter:
  rules:
    - close_sinks
    - avoid_void_async
  