name: Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1

      - name: Tests
        run: flutter test
        
      - name: Create APK
        run: flutter pub get && flutter build apk --release
          
      - uses: actions/upload-artifact@v2
        with:
          name: Release APK
          path: build/app/outputs/flutter-apk/app-release.apk
        
